### ISSUE TITLE
3. 食材をカテゴリごとに分けて、ユーザーが探しやすいようにする。

### ISSUE THREAD

**Issue by znrysk** [znrysk/nutrients_cal#6]
checkbox.htmlのstyle(css)部分を変更して、食材のチェックボックスがカテゴリごとに表示されるようにレイアウトし直します。

**Comment by bookcherry** [comment]
checkbox.htmlを変更し、食材を分類分けしました。

**Comment by znrysk** [comment]
ありがとうございます。
